### ISSUE TITLE
[logging] Ошибка логов

### ISSUE THREAD

**Issue by BU-Marina** [BU-Marina/BU-Marina#1]
### Текст ошибки:

`--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 74, in emit
    self.doRollover()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 179, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 115, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\FSDev\\LinguistaAPI\\logs\\general.log' -> 'C:\\FSDev\\LinguistaAPI\\logs\\general.log.1'
Call stack:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 683, in process_request_thread 
    self.finish_request(request, client_address)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\servers\basehttp.py", line 227, in handle
    self.handle_one_request()
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\servers\basehttp.py", line 252, in handle_one_request  
    handler.run(self.server.get_app())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__      
    return self.application(environ, start_response)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\utils\deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\whitenoise\middleware.py", line 124, in __call__
    return self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\utils\deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\utils\deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\corsheaders\middleware.py", line 56, in __call__
    result = self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\utils\deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\utils\deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\utils\deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\utils\deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\utils\deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "C:\FSDev\LinguistaAPI\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\FSDev\LinguistaAPI\config\middleware\db_queries_log.py", line 33, in __call__
    queries_logger.info(
Message: {'total execution time': 0.016, 'total number of queries': 40}
Arguments: ()`

**Comment by BU-Marina** [comment]
#### Появляется, когда размер файла с логами превосходит ограничения, заданные в конфиге (новые файлы не создаются хэндлером RotatingFileHandler)
```
...
'handlers': {
        'console': {
            # "level": "DEBUG",
            'class': 'logging.StreamHandler',
            'filters': ['require_debug_true'],
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/general.log',
            'backupCount': 10,  # keep at most 10 log files
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'formatter': 'verbose',
        },
        'mail_admins': {
            # "level": "ERROR",
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'config.middleware.request_log': {
            'handlers': ['file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'config.middleware.db_queries_log': {
            'handlers': ['file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
            'filters': ['require_debug_true'],
        },
        '': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
...
```

**Comment by BU-Marina** [comment]
#### При удалении файла ошибка уходит

**Comment by BU-Marina** [comment]
### Найденные ответы:
- https://stackoverflow.com/questions/26830918/django-logging-rotating-files-not-working

**Comment by BU-Marina** [comment]
# Решено с помощью изменения порядка логгеров в конфиге (переноса django.request и django.security под кастомные мидлвари) + добавление 'delay': True в хэндлеры типа RotatingFileHandler

### Исправленный конфиг:
```
...
'handlers': {
        'console': {
            # "level": "DEBUG",
            'class': 'logging.StreamHandler',
            'filters': ['require_debug_true'],
            'formatter': 'verbose',
        },
        'general_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/general.log',
            'backupCount': 10,  # keep at most 10 log files
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'formatter': 'verbose',
            'delay': True,
        },
        'queries_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/queries.log',
            'backupCount': 5,  # keep at most 5 log files
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'formatter': 'verbose',
            'delay': True,
        },
        'mail_admins': {
            # "level": "ERROR",
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
'loggers': {
        'config.middleware.request_log': {
            'handlers': ['general_file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'config.middleware.db_queries_log': {
            'handlers': ['queries_file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
            'filters': ['require_debug_true'],
        },
        'django.request': {
            'handlers': ['mail_admins', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        '': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
...
```
